name: Docker Image CI

on:
  push:
    branches: [ 'production' ]
  # Publish semver tags as releases.
  tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate semantic version
      id: semver
      uses: ./.github/actions/semver-js
      with:
        mode: config-change
        config_file: version.txt
        tag_prefix: v
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=${{ steps.semver.outputs.version }}
          type=raw,value=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
          type=raw,value=${{ steps.semver.outputs.major }}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{ steps.semver.outputs.version }}
          BUILD_DATE=${{ steps.semver.outputs.build_date_utc }}
          VCS_REF=${{ steps.semver.outputs.sha }}
